name: Update inputs

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  update:
    if: github.repository == 'hyprwm/hyprnix'
    name: inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: hyprwm/actions/.github/actions/nix-setup.yaml@main

      - name: Update Inputs
        run: update.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[gha] Update inputs"
